language: java

env:

os:
  - linux

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

sudo: false

before_install:
  - chmod +x .travis_install.sh
  - chmod +x .travis_test.sh

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

branches:
  only:
    - master